import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Navbar from "@/components/ui/Navbar"
import { Provider } from "@/components/providers/Provider"

const inter = Inter({ subsets: ["latin-ext"], weight: "600" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='bg-zinc-950 text-white'>
      <body className={inter.className}>
        <Provider>
          <Navbar />
          <hr className='opacity-30'></hr>
          {children}
        </Provider>
      </body>
    </html>
  )
}
